# Indexação e fatiamento (slicing)

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([4, 4, 8, 3, 3, 3, 6, 7, 7, 7])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[ 58,  95,  45,  24,  15],
       [100,  59,  41,   2,  43],
       [ 48,  51,  65,  81,  49],
       [ 87,  97,  30,  28,  31]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.16416304, 0.03675595, 0.64858261, 0.24127851, 0.66235902],
        [0.42341172, 0.82179755, 0.83839468, 0.99972187, 0.00921451],
        [0.15991195, 0.50344771, 0.50345988, 0.48224493, 0.03509879],
        [0.50551981, 0.20537035, 0.09255965, 0.76102855, 0.72310482]],

       [[0.46057761, 0.57778226, 0.29896016, 0.12702409, 0.21890134],
        [0.81535964, 0.20674744, 0.71977994, 0.90790432, 0.04077622],
        [0.67512431, 0.36391203, 0.54395143, 0.58395841, 0.15251024],
        [0.83544593, 0.17106912, 0.95177966, 0.38904965, 0.91118999]],

       [[0.92658815, 0.6770264 , 0.92735042, 0.70725533, 0.55282373],
        [0.16698611, 0.68721311, 0.08719852, 0.90405247, 0.39137554],
        [0.02085785, 0.76043026, 0.45558854, 0.90483183, 0.92062908],
        [0.86953142, 0.53992999, 0.95984249, 0.2983721 , 0.21814162]]])

### Acessando elementos específicos

In [5]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([4, 4, 8, 3, 3, 3, 6, 7, 7, 7])

In [6]:
# nome_do_array[índice]
a1D[0]

4

In [7]:
a1D[2]

8

In [8]:
a1D[-1]

7

In [9]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([3, 4, 7])

In [10]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[ 58,  95,  45,  24,  15],
       [100,  59,  41,   2,  43],
       [ 48,  51,  65,  81,  49],
       [ 87,  97,  30,  28,  31]])

In [11]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

41

In [12]:
a2D[3][4]

31

In [13]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([58, 59, 65, 28])

In [14]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([24, 41, 51, 87])

In [15]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([28, 65, 59, 58])

In [16]:
a2D[:,[0,1,2,0]] 

array([[ 58,  95,  45,  58],
       [100,  59,  41, 100],
       [ 48,  51,  65,  48],
       [ 87,  97,  30,  87]])

In [17]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[100,  59,  41, 100],
       [ 58,  95,  45,  58],
       [100,  59,  41, 100],
       [ 58,  95,  45,  58]])

In [18]:
a2D

array([[ 58,  95,  45,  24,  15],
       [100,  59,  41,   2,  43],
       [ 48,  51,  65,  81,  49],
       [ 87,  97,  30,  28,  31]])

In [19]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[100,  59,  41, 100],
       [ 58,  95,  45,  58],
       [100,  59,  41, 100],
       [ 58,  95,  45,  58]])

In [20]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.16416304, 0.03675595, 0.64858261, 0.24127851, 0.66235902],
        [0.42341172, 0.82179755, 0.83839468, 0.99972187, 0.00921451],
        [0.15991195, 0.50344771, 0.50345988, 0.48224493, 0.03509879],
        [0.50551981, 0.20537035, 0.09255965, 0.76102855, 0.72310482]],

       [[0.46057761, 0.57778226, 0.29896016, 0.12702409, 0.21890134],
        [0.81535964, 0.20674744, 0.71977994, 0.90790432, 0.04077622],
        [0.67512431, 0.36391203, 0.54395143, 0.58395841, 0.15251024],
        [0.83544593, 0.17106912, 0.95177966, 0.38904965, 0.91118999]],

       [[0.92658815, 0.6770264 , 0.92735042, 0.70725533, 0.55282373],
        [0.16698611, 0.68721311, 0.08719852, 0.90405247, 0.39137554],
        [0.02085785, 0.76043026, 0.45558854, 0.90483183, 0.92062908],
        [0.86953142, 0.53992999, 0.95984249, 0.2983721 , 0.21814162]]])

In [21]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.7072553348408113

In [22]:
a3D[0][3][1]

0.205370354358539

### Fatiamento (slicing)

In [23]:
# Array de 1 dimensão
a1D

array([4, 4, 8, 3, 3, 3, 6, 7, 7, 7])

In [24]:
a = a1D[1:5] # Índice 1 ao 4
a

array([4, 8, 3, 3])

In [25]:
b = a1D[0:6] # Índice 0 ao 5
b

array([4, 4, 8, 3, 3, 3])

In [26]:
c = a1D[:6] # Do início ao 5
c

array([4, 4, 8, 3, 3, 3])

In [27]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([4, 8, 3, 6, 7])

In [28]:
e = a1D[-1::-1] # Do final até o início
e

array([7, 7, 7, 6, 3, 3, 3, 8, 4, 4])

In [29]:
# Array de 2 dimensões
a2D

array([[ 58,  95,  45,  24,  15],
       [100,  59,  41,   2,  43],
       [ 48,  51,  65,  81,  49],
       [ 87,  97,  30,  28,  31]])

In [30]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([58, 95, 45, 24, 15])

In [31]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

array([100,  59,  41,   2,  43])

In [32]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([51, 65, 81])

In [33]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

array([87, 97, 30, 28, 31])

In [34]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([45, 41, 65, 30])

In [35]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([ 2, 81, 28])

In [36]:
# Array de 3 dimensões
a3D

array([[[0.16416304, 0.03675595, 0.64858261, 0.24127851, 0.66235902],
        [0.42341172, 0.82179755, 0.83839468, 0.99972187, 0.00921451],
        [0.15991195, 0.50344771, 0.50345988, 0.48224493, 0.03509879],
        [0.50551981, 0.20537035, 0.09255965, 0.76102855, 0.72310482]],

       [[0.46057761, 0.57778226, 0.29896016, 0.12702409, 0.21890134],
        [0.81535964, 0.20674744, 0.71977994, 0.90790432, 0.04077622],
        [0.67512431, 0.36391203, 0.54395143, 0.58395841, 0.15251024],
        [0.83544593, 0.17106912, 0.95177966, 0.38904965, 0.91118999]],

       [[0.92658815, 0.6770264 , 0.92735042, 0.70725533, 0.55282373],
        [0.16698611, 0.68721311, 0.08719852, 0.90405247, 0.39137554],
        [0.02085785, 0.76043026, 0.45558854, 0.90483183, 0.92062908],
        [0.86953142, 0.53992999, 0.95984249, 0.2983721 , 0.21814162]]])

In [37]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.46057761, 0.57778226, 0.29896016, 0.12702409, 0.21890134],
       [0.81535964, 0.20674744, 0.71977994, 0.90790432, 0.04077622],
       [0.67512431, 0.36391203, 0.54395143, 0.58395841, 0.15251024],
       [0.83544593, 0.17106912, 0.95177966, 0.38904965, 0.91118999]])

In [38]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.57778226, 0.29896016, 0.12702409],
       [0.20674744, 0.71977994, 0.90790432],
       [0.36391203, 0.54395143, 0.58395841]])

In [39]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.15991195, 0.50344771, 0.50345988, 0.48224493, 0.03509879])

In [40]:
a3D

array([[[0.16416304, 0.03675595, 0.64858261, 0.24127851, 0.66235902],
        [0.42341172, 0.82179755, 0.83839468, 0.99972187, 0.00921451],
        [0.15991195, 0.50344771, 0.50345988, 0.48224493, 0.03509879],
        [0.50551981, 0.20537035, 0.09255965, 0.76102855, 0.72310482]],

       [[0.46057761, 0.57778226, 0.29896016, 0.12702409, 0.21890134],
        [0.81535964, 0.20674744, 0.71977994, 0.90790432, 0.04077622],
        [0.67512431, 0.36391203, 0.54395143, 0.58395841, 0.15251024],
        [0.83544593, 0.17106912, 0.95177966, 0.38904965, 0.91118999]],

       [[0.92658815, 0.6770264 , 0.92735042, 0.70725533, 0.55282373],
        [0.16698611, 0.68721311, 0.08719852, 0.90405247, 0.39137554],
        [0.02085785, 0.76043026, 0.45558854, 0.90483183, 0.92062908],
        [0.86953142, 0.53992999, 0.95984249, 0.2983721 , 0.21814162]]])

In [41]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.42341172, 0.82179755, 0.83839468, 0.99972187, 0.00921451],
       [0.81535964, 0.20674744, 0.71977994, 0.90790432, 0.04077622],
       [0.16698611, 0.68721311, 0.08719852, 0.90405247, 0.39137554]])

In [42]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.24127851, 0.99972187, 0.48224493, 0.76102855],
       [0.12702409, 0.90790432, 0.58395841, 0.38904965],
       [0.70725533, 0.90405247, 0.90483183, 0.2983721 ]])

### Indexação com booleanos

In [43]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[151,  55,  55, 395, 145, 371, 474, 382],
       [146, 402, 101, 205, 179, 312,   3, 404],
       [ 48, 222, 165, 269, 260, 336, 116,  77],
       [333, 197, 462, 404,  37, 187,  55, 134],
       [489,  90, 447, 267, 203, 405, 117, 291],
       [284,  80, 425,  85, 180, 140, 232, 486],
       [199, 287, 270, 483, 286,  88, 102, 363],
       [476, 354,  95, 165, 138, 362, 200, 491],
       [434, 118, 211, 203, 459,  91, 331, 168],
       [112, 364, 235, 377, 193, 206, 426, 209]])

In [44]:
a2D >= 250

array([[False, False, False,  True, False,  True,  True,  True],
       [False,  True, False, False, False,  True, False,  True],
       [False, False, False,  True,  True,  True, False, False],
       [ True, False,  True,  True, False, False, False, False],
       [ True, False,  True,  True, False,  True, False,  True],
       [ True, False,  True, False, False, False, False,  True],
       [False,  True,  True,  True,  True, False, False,  True],
       [ True,  True, False, False, False,  True, False,  True],
       [ True, False, False, False,  True, False,  True, False],
       [False,  True, False,  True, False, False,  True, False]])

In [45]:
a2D[a2D >= 250]

array([395, 371, 474, 382, 402, 312, 404, 269, 260, 336, 333, 462, 404,
       489, 447, 267, 405, 291, 284, 425, 486, 287, 270, 483, 286, 363,
       476, 354, 362, 491, 434, 459, 331, 364, 377, 426])

In [46]:
a2D.mean()

247.4875

In [47]:
a2D[a2D <= a2D.mean()]

array([151,  55,  55, 145, 146, 101, 205, 179,   3,  48, 222, 165, 116,
        77, 197,  37, 187,  55, 134,  90, 203, 117,  80,  85, 180, 140,
       232, 199,  88, 102,  95, 165, 138, 200, 118, 211, 203,  91, 168,
       112, 235, 193, 206, 209])