# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([5, 7, 0, 0, 0, 2, 7, 5, 4, 6])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[48, 97, 14, 57, 22],
       [61, 61, 89, 71, 38],
       [79, 17, 71, 91, 50],
       [14, 91, 45, 77, 48]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.5846658 , 0.24768408, 0.51716679, 0.70217822, 0.09067263],
        [0.40427792, 0.9469927 , 0.44743307, 0.58654135, 0.23482644],
        [0.59777108, 0.95012025, 0.3206822 , 0.63117955, 0.24227402],
        [0.75273599, 0.16597755, 0.18148721, 0.34894842, 0.33966796]],

       [[0.63104241, 0.48569692, 0.07851499, 0.12568566, 0.41665633],
        [0.53817889, 0.7788968 , 0.99995881, 0.82340131, 0.81537874],
        [0.16585968, 0.13751098, 0.37601356, 0.8384131 , 0.9663049 ],
        [0.65924729, 0.07781796, 0.1136514 , 0.21588365, 0.21966188]],

       [[0.66990945, 0.17133606, 0.0720167 , 0.59679672, 0.50943077],
        [0.6583785 , 0.57161255, 0.31645507, 0.52145098, 0.1612439 ],
        [0.20308189, 0.61664061, 0.1679762 , 0.46436753, 0.65585456],
        [0.31392196, 0.97001071, 0.47404358, 0.78121548, 0.04192702]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [6]:
a2D.shape

(4, 5)

In [7]:
a3D.shape

(3, 4, 5)

In [8]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [9]:
a2D.ndim

2

In [10]:
a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [11]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [12]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [13]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [14]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [15]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [16]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [17]:
a1D.size

10

In [18]:
a2D.size

20

In [19]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [20]:
a1D.dtype

dtype('int32')

In [21]:
a1D.dtype.name

'int32'

In [22]:
a2D.dtype

dtype('int32')

In [23]:
a2D.dtype.name

'int32'

In [24]:
a3D.dtype

dtype('float64')

In [25]:
a3D.dtype.name

'float64'