# Manipulação de arrays Numpy

### Importando o NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Alterando, adicionando e removendo elementos

In [98]:
# Criando um array de 1 dimensão
a1D = np.random.randint(1,200, 12)
a1D

array([195, 116, 105,  84, 188,  63, 107,  83,  74,  70,  61,  96])

In [3]:
# Criando um array de 2 dimensões
a2D = np.random.randint(1,200, (3,4))
a2D

array([[131,  36,  16,  35],
       [136,  52,  83,  29],
       [112, 147,  39,  28]])

In [4]:
# Criando um array de 3 dimensões
a3D = np.random.randint(1,200, (2,3,6)) # 2 páginas/faces, 3 linhas, 6 colunas
a3D

array([[[ 51, 151,  86,  54,  92,  98],
        [ 85, 133, 143,  47, 152, 102],
        [ 91, 176, 101,  92, 132,  35]],

       [[157, 117, 115,  49, 182,  87],
        [119, 117, 127, 192,  72, 155],
        [ 94, 196,  72,  26, 122, 168]]])

In [5]:
# Alterando o elemento do índice 0
a1D[0] = -1
a1D

array([ -1, 155,  15, 171, 158,  77, 134,  29, 143,  41, 158,   1])

In [6]:
# Alterando o elemento da linha 1, coluna 2
a2D[1][2] = -1
a2D

array([[131,  36,  16,  35],
       [136,  52,  -1,  29],
       [112, 147,  39,  28]])

In [7]:
# Alterando o elemento da face 1, linha 2, coluna 4
a3D[1][2][4] = -1
a3D

array([[[ 51, 151,  86,  54,  92,  98],
        [ 85, 133, 143,  47, 152, 102],
        [ 91, 176, 101,  92, 132,  35]],

       [[157, 117, 115,  49, 182,  87],
        [119, 117, 127, 192,  72, 155],
        [ 94, 196,  72,  26,  -1, 168]]])

In [101]:
# Retorna array com elementos adicionados no final
a1D_modificado = np.append(a1D, [100, 130])
a1D_modificado

array([195, 116, 105,  84, 188,  63, 107,  83,  74,  70,  61,  96, 100,
       130])

In [102]:
a1D # a1D não foi modificado

array([195, 116, 105,  84, 188,  63, 107,  83,  74,  70,  61,  96])

In [10]:
a2D_modificado = np.append(a2D, [100, 130]) # Lineariza a2D e insere os elementos no final
a2D_modificado

array([131,  36,  16,  35, 136,  52,  -1,  29, 112, 147,  39,  28, 100,
       130])

In [11]:
a2D # a2D não foi modificado

array([[131,  36,  16,  35],
       [136,  52,  -1,  29],
       [112, 147,  39,  28]])

In [12]:
a3D_modificado = np.append(a3D, [100, 130]) # Lineariza a3D e insere os elementos no final
a3D_modificado

array([ 51, 151,  86,  54,  92,  98,  85, 133, 143,  47, 152, 102,  91,
       176, 101,  92, 132,  35, 157, 117, 115,  49, 182,  87, 119, 117,
       127, 192,  72, 155,  94, 196,  72,  26,  -1, 168, 100, 130])

In [13]:
a3D # a3D não foi modificado

array([[[ 51, 151,  86,  54,  92,  98],
        [ 85, 133, 143,  47, 152, 102],
        [ 91, 176, 101,  92, 132,  35]],

       [[157, 117, 115,  49, 182,  87],
        [119, 117, 127, 192,  72, 155],
        [ 94, 196,  72,  26,  -1, 168]]])

In [14]:
a1D_modificado2 = np.delete(a1D_modificado, [0, 1, 3])
print(a1D_modificado)
print(a1D_modificado2)

[ -1 155  15 171 158  77 134  29 143  41 158   1 100 130]
[ 15 158  77 134  29 143  41 158   1 100 130]


### Comparação entre arrays

In [15]:
a1D = np.array([1, 2, 3, 4, 5])
b1D = np.array([3, 2, 1, 4, 5])
a1D == b1D # Comparação elemento a elemento

array([False,  True, False,  True,  True])

In [16]:
c1D = np.random.randint(1,10,20)
c1D

array([2, 2, 6, 2, 9, 2, 9, 9, 4, 8, 7, 3, 5, 3, 1, 5, 7, 7, 2, 7])

In [17]:
c1D == 5

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False])

In [18]:
c1D[c1D == 5]

array([5, 5])

### Operações entre arrays e escalares

In [19]:
a1D = np.arange(1,11)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
b1D = np.arange(1,20,2)
b1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
c1D = 2 * a1D # Cada elemento de a1D será multiplicado por 2
c1D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
d1D = b1D + 5 # Soma 5 para cada elemento de b1D
d1D

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [23]:
e1D = b1D - 3
e1D

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [24]:
f1D = a1D / 5
f1D

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [25]:
celsius = np.arange(-20, 36) # Cria um array com o valores de -20 a 35, representando a temperatura em graus Celsius
fahrenheit = celsius * (9/5) + 32 # Cria um array convertendo cada valor em Celsius para fahrenheit

fahrenheit

array([-4. , -2.2, -0.4,  1.4,  3.2,  5. ,  6.8,  8.6, 10.4, 12.2, 14. ,
       15.8, 17.6, 19.4, 21.2, 23. , 24.8, 26.6, 28.4, 30.2, 32. , 33.8,
       35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. , 51.8, 53.6,
       55.4, 57.2, 59. , 60.8, 62.6, 64.4, 66.2, 68. , 69.8, 71.6, 73.4,
       75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. , 87.8, 89.6, 91.4, 93.2,
       95. ])

In [26]:
# Somando cada elemento de a1D a b1D
g1D = a1D + b1D
print(a1D)
print(b1D)
print("-"*31)
print(g1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [27]:
# Outra forma de somar cada elemento de a1D a b1D
h1D = np.add(a1D, b1D)
print(a1D)
print(b1D)
print("-"*31)
print(h1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [28]:
i1D = h1D - g1D
print(h1D)
print(g1D)
print("-"*31)
print(i1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [29]:
# Outra forma de somar cada elemento de a1D a b1D
j1D = np.subtract(h1D, g1D)
print(h1D)
print(g1D)
print("-"*31)
print(j1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [30]:
a1D = np.arange(1, 6)
a1D

array([1, 2, 3, 4, 5])

In [31]:
b1D = np.arange(6,11)
b1D

array([ 6,  7,  8,  9, 10])

In [32]:
c1D = a1D * b1D
c1D

array([ 6, 14, 24, 36, 50])

In [33]:
d1D = np.multiply(a1D, b1D)
d1D

array([ 6, 14, 24, 36, 50])

In [34]:
e1D = c1D / a1D
e1D

array([ 6.,  7.,  8.,  9., 10.])

In [35]:
f1D = np.divide(c1D, a1D)
f1D

array([ 6.,  7.,  8.,  9., 10.])

In [36]:
g1D = np.arange(1,10)
g1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
raiz1D = np.sqrt(g1D)
raiz1D

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### Algumas funções

In [38]:
d2D = np.random.randint(1, 101, (5,10)) # Array de 5 linhas x 10 colunas preenchidos com valores aleatórios entre 1 e 100
d2D

array([[13, 39, 55, 45, 88, 18, 69,  3, 34, 41],
       [ 6,  2, 82, 65, 88, 24, 59, 17, 56,  7],
       [17,  8, 37, 49, 41, 60,  4, 28, 45, 97],
       [21, 47, 27,  2, 66, 11, 70, 70, 34, 15],
       [41, 45, 79, 87, 25, 38, 63, 31, 69, 69]])

#### Obs: como os valores valores são gerados aleatoriamente, sua matriz provavelmente será diferente da gerada acima

In [39]:
# Soma de todos os elementos
d2D.sum()

2107

In [40]:
# Soma de todos os elementos de cada coluna (eixo 0)
d2D.sum(axis = 0)

array([ 98, 141, 280, 248, 308, 151, 265, 149, 238, 229])

In [41]:
# Soma de todos os elementos de cada linha (eixo 1)
d2D.sum(axis = 1)

array([405, 406, 386, 363, 547])

In [42]:
somacol = sum(d2D) # A função sum() do Python retornará a soma de todas as colunas
somacol

array([ 98, 141, 280, 248, 308, 151, 265, 149, 238, 229])

In [43]:
# Retorna o menor valor geral
d2D.min()

2

In [44]:
# Retorna o menor valor de cada coluna (eixo 0)
d2D.min(axis=0)

array([ 6,  2, 27,  2, 25, 11,  4,  3, 34,  7])

In [45]:
# Retorna o menor valor de cada linha (eixo 1)
d2D.min(axis=1)

array([ 3,  2,  4,  2, 25])

In [46]:
# Retorna o maior valor geral
d2D.max()

97

In [47]:
# Retorna o maior valor de cada coluna (eixo 0)
d2D.max(axis=0)

array([41, 47, 82, 87, 88, 60, 70, 70, 69, 97])

In [48]:
# Retorna o maior valor de cada linha (eixo 1)
d2D.max(axis=1)

array([88, 88, 97, 70, 87])

In [49]:
# Retorna a soma cumulativa
d2D.cumsum()

array([  13,   52,  107,  152,  240,  258,  327,  330,  364,  405,  411,
        413,  495,  560,  648,  672,  731,  748,  804,  811,  828,  836,
        873,  922,  963, 1023, 1027, 1055, 1100, 1197, 1218, 1265, 1292,
       1294, 1360, 1371, 1441, 1511, 1545, 1560, 1601, 1646, 1725, 1812,
       1837, 1875, 1938, 1969, 2038, 2107])

In [50]:
# Retorna a soma cumulativa para cada coluna (eixo = 0)
d2D.cumsum(axis = 0)

array([[ 13,  39,  55,  45,  88,  18,  69,   3,  34,  41],
       [ 19,  41, 137, 110, 176,  42, 128,  20,  90,  48],
       [ 36,  49, 174, 159, 217, 102, 132,  48, 135, 145],
       [ 57,  96, 201, 161, 283, 113, 202, 118, 169, 160],
       [ 98, 141, 280, 248, 308, 151, 265, 149, 238, 229]])

In [51]:
d2D

array([[13, 39, 55, 45, 88, 18, 69,  3, 34, 41],
       [ 6,  2, 82, 65, 88, 24, 59, 17, 56,  7],
       [17,  8, 37, 49, 41, 60,  4, 28, 45, 97],
       [21, 47, 27,  2, 66, 11, 70, 70, 34, 15],
       [41, 45, 79, 87, 25, 38, 63, 31, 69, 69]])

In [52]:
# Retorna a soma cumulativa para cada linha (eixo = 1)
x = d2D.cumsum(axis = 1)
x

array([[ 13,  52, 107, 152, 240, 258, 327, 330, 364, 405],
       [  6,   8,  90, 155, 243, 267, 326, 343, 399, 406],
       [ 17,  25,  62, 111, 152, 212, 216, 244, 289, 386],
       [ 21,  68,  95,  97, 163, 174, 244, 314, 348, 363],
       [ 41,  86, 165, 252, 277, 315, 378, 409, 478, 547]])

In [53]:
# Retorna a média aritmética
d2D.mean()

42.14

In [54]:
# Retorna a média aritmética para cada coluna (eixo = 0)
d2D.mean(axis = 0)

array([19.6, 28.2, 56. , 49.6, 61.6, 30.2, 53. , 29.8, 47.6, 45.8])

In [55]:
# Retorna a média aritmética para cada linha (eixo = 1)
d2D.mean(axis = 1)

array([40.5, 40.6, 38.6, 36.3, 54.7])

In [56]:
# Retorna o desvio padrão
d2D.std()

26.308181237022072

In [57]:
# Retorna o desvio padrão para cada coluna (eixo = 0)
d2D.std(axis = 0)

array([11.79152238, 19.21874085, 21.94538676, 28.01142624, 25.20793526,
       17.34819875, 24.82740421, 22.37319825, 13.45511055, 33.57618203])

In [58]:
# Retorna o desvio padrão para cada linha (eixo = 1)
d2D.std(axis = 1)

array([24.52039967, 31.27363107, 25.9584283 , 24.21590387, 20.2881739 ])

In [59]:
# Retorna a mediana (geral)
np.median(d2D)

41.0

In [60]:
# Retorna a mediana para cada coluna (eixo = 0)
np.median(d2D, axis = 0)

array([17., 39., 55., 49., 66., 24., 63., 28., 45., 41.])

In [61]:
# Retorna a mediana para cada linha (eixo = 1)
np.median(d2D, axis = 1)

array([40. , 40. , 39. , 30.5, 54. ])

### Copiando e concatenando arrays

In [62]:
a2D = np.random.randint(1,50, (4,5))
a2D

array([[14, 21, 30, 49, 41],
       [19, 16, 18, 46, 27],
       [ 8, 38, 45, 40, 38],
       [44, 34, 31, 32,  6]])

In [63]:
b2D = np.random.randint(50,100, (4,5))
b2D

array([[50, 65, 74, 58, 56],
       [88, 56, 73, 60, 74],
       [98, 58, 98, 85, 69],
       [77, 61, 65, 98, 72]])

In [64]:
c2D = a2D
c2D

array([[14, 21, 30, 49, 41],
       [19, 16, 18, 46, 27],
       [ 8, 38, 45, 40, 38],
       [44, 34, 31, 32,  6]])

In [65]:
# Aparentemente ocorreu uma cópia dos arrays, mas veja o que acontece se alterarmos alguns elementos
c2D[c2D < 20] = -1
c2D

array([[-1, 21, 30, 49, 41],
       [-1, -1, -1, 46, 27],
       [-1, 38, 45, 40, 38],
       [44, 34, 31, 32, -1]])

In [66]:
a2D 

array([[-1, 21, 30, 49, 41],
       [-1, -1, -1, 46, 27],
       [-1, 38, 45, 40, 38],
       [44, 34, 31, 32, -1]])

Os elementos de a2D também foram alterados. :-(

In [67]:
# Redefinindo os elementos de a2D
a2D = np.random.randint(1,50, (4,5))
a2D

array([[14, 45, 36, 45, 30],
       [ 7, 40,  9, 12, 30],
       [43, 22, 39, 42, 21],
       [ 3, 48,  1, 41, 20]])

In [68]:
# Forma correta de copiar um array parece que com a forma de copiar uma lista
c2D = a2D.copy()
c2D

array([[14, 45, 36, 45, 30],
       [ 7, 40,  9, 12, 30],
       [43, 22, 39, 42, 21],
       [ 3, 48,  1, 41, 20]])

In [69]:
c2D[c2D < 20] = -1
c2D

array([[-1, 45, 36, 45, 30],
       [-1, 40, -1, -1, 30],
       [43, 22, 39, 42, 21],
       [-1, 48, -1, 41, 20]])

In [70]:
a2D

array([[14, 45, 36, 45, 30],
       [ 7, 40,  9, 12, 30],
       [43, 22, 39, 42, 21],
       [ 3, 48,  1, 41, 20]])

Agora sim!!!

### Ordenando os elementos de um array

In [71]:
a1D = np.random.randint(1,100, 15)
a1D

array([47, 70,  6, 48, 97, 93, 19, 42, 63, 32, 39, 10, 78, 65, 62])

In [72]:
a1D.sort()
a1D

array([ 6, 10, 19, 32, 39, 42, 47, 48, 62, 63, 65, 70, 78, 93, 97])

In [73]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[91, 77, 68,  8, 47, 66, 45, 58, 51,  2],
       [93, 33, 44, 75, 15, 42, 50, 14,  1, 79],
       [38, 74, 92, 49, 16, 92,  7,  9, 86, 58],
       [37, 33, 55, 94,  6,  5, 64, 44, 17, 21],
       [53, 22, 45, 13, 91, 66, 41, 12, 65, 53],
       [13, 69, 59, 39, 95, 71, 33, 24, 91, 17]])

In [74]:
a2D.sort() # Por padrão ordena o maior eixo (nesse caso o eixo 1, linhas)
a2D

array([[ 2,  8, 45, 47, 51, 58, 66, 68, 77, 91],
       [ 1, 14, 15, 33, 42, 44, 50, 75, 79, 93],
       [ 7,  9, 16, 38, 49, 58, 74, 86, 92, 92],
       [ 5,  6, 17, 21, 33, 37, 44, 55, 64, 94],
       [12, 13, 22, 41, 45, 53, 53, 65, 66, 91],
       [13, 17, 24, 33, 39, 59, 69, 71, 91, 95]])

In [75]:
a2D.sort(axis=0) # Ordenando pelo eixo 0 (colunas)
a2D

array([[ 1,  6, 15, 21, 33, 37, 44, 55, 64, 91],
       [ 2,  8, 16, 33, 39, 44, 50, 65, 66, 91],
       [ 5,  9, 17, 33, 42, 53, 53, 68, 77, 92],
       [ 7, 13, 22, 38, 45, 58, 66, 71, 79, 93],
       [12, 14, 24, 41, 49, 58, 69, 75, 91, 94],
       [13, 17, 45, 47, 51, 59, 74, 86, 92, 95]])

In [76]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[56, 25, 40, 51, 70, 75, 17, 88,  6, 28],
       [94, 53, 70, 25,  7, 94, 15, 39, 34, 27],
       [36, 69, 27,  4, 76, 38, 58,  6, 30, 75],
       [88, 80, 35, 60, 60, 73,  8, 42, 66,  1],
       [ 7, 33, 11, 10, 75, 54, 45, 88, 44, 57],
       [91, 47, 91, 15, 61, 20, 54, 94,  3,  4]])

In [77]:
a2D.sort(axis=1) # Ordenando pelo eixo 1 (linhas)
a2D

array([[ 6, 17, 25, 28, 40, 51, 56, 70, 75, 88],
       [ 7, 15, 25, 27, 34, 39, 53, 70, 94, 94],
       [ 4,  6, 27, 30, 36, 38, 58, 69, 75, 76],
       [ 1,  8, 35, 42, 60, 60, 66, 73, 80, 88],
       [ 7, 10, 11, 33, 44, 45, 54, 57, 75, 88],
       [ 3,  4, 15, 20, 47, 54, 61, 91, 91, 94]])

### Transposição de arrays

In [78]:
a2D = np.array([[1,2,3,4],[5,6,7,8]])
a2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
a2DT = a2D.T # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [80]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
a2D.transpose() # Retorna a transposta

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [82]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Mudando o formato de um array - reshape()

In [83]:
a1D = np.arange(1,25)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [84]:
print(a1D.shape)
a1D.shape = (2,12)
print(a1D.shape)
print(a1D)

(24,)
(2, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [85]:
a2D_4x6 = a1D.reshape(4,6)
a2D_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [86]:
a1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [87]:
a2D_3x8 = a1D.reshape(3,8)
a2D_3x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

### Linearização de um array

In [88]:
x = a2D_3x8.flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [89]:
y = a2D_3x8.ravel()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Combinando/concatenando arrays

In [90]:
a2D = np.random.randint(1,101,(3,9))
a2D

array([[49,  2, 35,  6, 39,  4, 70, 57, 87],
       [30, 32, 14, 98, 79, 97, 38, 96, 79],
       [53, 94, 66, 81, 47, 33, 19, 22, 99]])

In [91]:
b2D = np.random.randint(1,101,(5,9))
b2D

array([[ 7, 73, 55, 88, 19, 57,  3, 83, 15],
       [86, 16,  2, 76, 57, 16, 64, 99, 25],
       [18, 81,  2, 68, 35, 98, 38, 65, 85],
       [57, 94, 18, 75,  8, 30, 77, 70, 49],
       [62, 86, 58, 43, 50, 14, 21, 48, 61]])

In [92]:
c2D = np.random.randint(1,101,(5,4))
c2D

array([[ 18,  57,  73,  58],
       [ 26,  18,  22,  75],
       [ 55,  62,  83,  96],
       [ 60,  16,   3,  90],
       [ 91, 100,  74,  28]])

In [93]:
# Concatenação de strings usa o operador "+"
str1 = "Python"
str2 = " & "
str3 = "Numpy"
str4 = str1 + str2 + str3
str4

'Python & Numpy'

In [94]:
# O operador "+" aplicado a ndarrays não faz a concatenação, mas tentar somar elemento a elemento
a2D + b2D

ValueError: operands could not be broadcast together with shapes (3,9) (5,9) 

In [ ]:
A = np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(A)

In [ ]:
B = np.vstack((a2D, b2D)) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(B)

In [ ]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(C)

In [ ]:
D = np.hstack((b2D, c2D)) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(D)

### Dividindo arrays

In [ ]:
A_splitted = np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted[0])
print("")
print("2a parte")
print(A_splitted[1])

In [ ]:
A_splitted3 = np.hsplit(A,3) # Divisão horizontal (corta no sentido das linhas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted3[0])
print("")
print("2a parte")
print(A_splitted3[1])
print("")
print("3a parte")
print(A_splitted3[2])