### Pergunta 1

Qual é a saída correta para o código Python a seguir?


```
    import numpy as np
    dataset = np.array(['paul', 'jacob', 'vince', 'paul', 'miky', 'larence', 'warren'])
    print(dataset == 'paul')
```



**A) [True False False True False False False]**

B) True

C) [False False False True False False False]

D) [True False False False False False False]

In [14]:
import numpy as np
dataset = np.array(['paul', 'jacob', 'vince', 'paul', 'miky', 'larence', 'warren'])
print(dataset == 'paul')

[ True False False  True False False False]


### Pergunta 2

Quais das opções substituem todos os números pares do array abaixo por -1?

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`


**A) arr[::2] = -1**

B) arr[1::2] = -1

**C) arr[arr % 2 == 0] = -1**

**D) arr[-2::-2] = -1**

In [15]:
def create_array():
    return np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[::2] = -1 
print(arr)

arr = create_array()
arr[1::2] = -1
print(arr)

arr = create_array()
arr[arr % 2 == 0] = -1 
print(arr)

arr = create_array()
arr[-2::-2] = -1 
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[-1  1 -1  3 -1  5 -1  7 -1  9]
[-1  1 -1  3 -1  5 -1  7 -1  9]


### Pergunta 3

Qual a saída correta para código a seguir?

```
import numpy as np
series = [[23,45,12,679], [14,48,69,38]]
new_series = np.array(series)
print(new_series.ndim)
print(new_series.shape)
```

**A) 2 (2, 4)**

B) 2 (4, 2)

C) 4 (2)

D) 2 (4)

In [16]:
series = [[23,45,12,679], [14,48,69,38]]
new_series = np.array(series)
print(new_series.ndim)
print(new_series.shape)

2
(2, 4)


## Pergunta 4

Vamos supor que eu queira criar um ndarray de uma dimensão, com 10 posições armazenando o valor 4. Quais das seguintes formas são corretas?
Grupo de escolhas da pergunta

**A) a = np.zeros(10) + 4**

B) a = np.zeros(10) * 4

**C) a = np.ones(10) * 4**

D) a= np.ones(10) + 4

**E) a = np.full(10, 4)**

In [17]:
a = np.zeros(10) + 4
print(a)

a = np.zeros(10) * 4
print(a)

a = np.ones(10) * 4
print(a)

a= np.ones(10) + 4
print(a)

a = np.full(10, 4)
print(a)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[4 4 4 4 4 4 4 4 4 4]


### Pergunta 5
Qual é a saída para o código a seguir?

```
import numpy as np

percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype.name)
 ```

**A) 'float64'**

B) 'int32'

C) 'str'

D) 'bool'

E) 'float'

In [18]:
percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype.name)

float64


### Pergunta 6
Após criar uma matriz identidade de 5x5, um programador deseja preencher os elementos acima e abaixo da diagonal principal com o número -1. Como ele pode fazer isso?

`arr = np.eye(5)`

**A) arr[arr == 0] = -1**

**B) arr[arr != 1] = -1**

C) arr = np.full((5x5),-1)

D) arr = arr - (np.eye(5) + 1)

In [23]:
arr = np.eye(5)
arr[arr == 0] = -1
print(arr)

arr[arr != 1] = -1
print(arr)

# arr = np.full((5x5),-1) retorna erro

arr = arr - (np.eye(5) + 1)
print(arr)


[[ 1. -1. -1. -1. -1.]
 [-1.  1. -1. -1. -1.]
 [-1. -1.  1. -1. -1.]
 [-1. -1. -1.  1. -1.]
 [-1. -1. -1. -1.  1.]]
[[ 1. -1. -1. -1. -1.]
 [-1.  1. -1. -1. -1.]
 [-1. -1.  1. -1. -1.]
 [-1. -1. -1.  1. -1.]
 [-1. -1. -1. -1.  1.]]
[[-1. -2. -2. -2. -2.]
 [-2. -1. -2. -2. -2.]
 [-2. -2. -1. -2. -2.]
 [-2. -2. -2. -1. -2.]
 [-2. -2. -2. -2. -1.]]
