# Exercícios de Python, NumPy e pandas

## Exercícios de Python

In [1]:
import pandas as pd
import numpy as np
import random

### 1. Crie uma lista com os números de 1 a 10 e exiba-a.

In [13]:
lista = list(range(1,11))
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
# Resposta:
lista = list(range(1, 6))
print(lista)

[1, 2, 3, 4, 5]


### 2. Inverta a lista criada no exercício anterior e exiba-a.

In [14]:
lista.reverse()
print(lista)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [11]:
# Resposta:
lista2.reverse()
print(lista)

[10  9  8  7  6  5  4  3  2  1]


### 3. Crie uma função que receba uma lista e retorne o maior valor da lista.

In [9]:
def max_value(lista):
  return lista.max()

print(max_value(lista))

10


In [ ]:
# Resposta:
def maior_valor(lista):
    return max(lista)

print(maior_valor(lista))

### 4. Crie um dicionário com os pares (1, 'a'), (2, 'b'), (3, 'c') e exiba-o.

In [10]:
dic = {1:"a",2:"b",3:"c"}
print(dic)

{1: 'a', 2: 'b', 3: 'c'}


In [ ]:
# Resposta:
dicionario = {1: 'a', 2: 'b', 3: 'c'}
print(dicionario)

### 5. Adicione um novo par (4, 'd') ao dicionário criado e exiba-o.

In [12]:
dic[4] = "d"
print(dic)

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


In [ ]:
# Resposta:
dicionario[4] = 'd'
print(dicionario)

## Exercícios de NumPy

### 6. Importe a biblioteca NumPy.

In [ ]:
# Resposta:
import numpy as np

### 7. Crie um array NumPy com os números de 1 a 10 e exiba-o.

In [16]:
lista = np.arange(1,11)
print(lista)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Resposta:
array = np.arange(1, 11)
print(array)

### 8. Calcule a média dos valores do array criado e exiba-a.

In [17]:
print(lista.mean())


5.5


In [ ]:
# Resposta:
media = np.mean(array)
print(media)

### 9. Crie um array 3x3 de zeros e exiba-o.

In [20]:
a3d = np.zeros((3,3))
a3d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Resposta:
array_zeros = np.zeros((3, 3))
print(array_zeros)

### 10. Crie um array 3x3 de uns e exiba-o.

In [21]:
a3d1 = np.ones((3,3))
a3d1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Resposta:
array_ones = np.ones((3, 3))
print(array_ones)

### 11. Crie um array 3x3 com valores aleatórios e exiba-o.

In [27]:
ar = np.random.random((3,3))
ar

array([[0.74459969, 0.95406037, 0.83538515],
       [0.02911359, 0.71414051, 0.58242735],
       [0.91664592, 0.03016571, 0.2807164 ]])

In [ ]:
# Resposta:
array_random = np.random.random((3, 3))
print(array_random)

### 12. Calcule a soma de todos os valores do array criado no exercício anterior e exiba-a.

In [29]:
soma = np.sum(ar)
soma

5.087254691360029

In [ ]:
# Resposta:
soma = np.sum(array_random)
print(soma)

## Exercícios de pandas

### 13. Importe a biblioteca pandas.

In [ ]:
# Resposta:
import pandas as pd

### 14. Crie um DataFrame com os dados: {'A': [1, 2, 3], 'B': [4, 5, 6]} e exiba-o.

In [31]:
dic =  {'A': [1, 2, 3], 'B': [4, 5, 6]}
df = pd.DataFrame(dic)
df

A  B
0  1  4
1  2  5
2  3  6

In [ ]:
# Resposta:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df)

### 15. Exiba as estatísticas descritivas do DataFrame criado.

In [32]:
df.describe()

A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

In [ ]:
# Resposta:
print(df.describe())

### 16. Adicione uma nova coluna 'C' ao DataFrame com os valores [7, 8, 9] e exiba-o.

In [33]:
df["C"] = [7, 8, 9]
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
# Resposta:
df['C'] = [7, 8, 9]
print(df)

### 17. Selecione apenas a coluna 'A' do DataFrame e exiba-a.

In [34]:
df["A"]

0    1
1    2
2    3
Name: A, dtype: int64

In [ ]:
# Resposta:
coluna_a = df['A']
print(coluna_a)

### 18. Selecione as linhas onde o valor da coluna 'B' é maior que 4 e exiba-as.

In [36]:
df[df["B"] > 4]

A  B  C
1  2  5  8
2  3  6  9

In [ ]:
# Resposta:
linhas_b_maior_que_4 = df[df['B'] > 4]
print(linhas_b_maior_que_4)

### 19. Crie um DataFrame a partir de um arquivo CSV (você pode criar um arquivo CSV fictício para este exercício).

In [37]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [43]:
df2 = pd.read_csv("/content/drive/MyDrive/puc_ia_ml/ex_19.csv")

In [ ]:
# Resposta (exemplo):
# df_csv = pd.read_csv('caminho_para_o_arquivo.csv')
# print(df_csv)

### 20. Agrupe o DataFrame do exercício anterior pela coluna 'A' e calcule a média das outras colunas.

In [49]:
grupo = df2.groupby("A").mean()
print(grupo)

     B     C
A           
1  5.5   8.5
2  6.5   9.5
3  7.5  10.5


In [ ]:
# Resposta (exemplo):
# df_agrupado = df_csv.groupby('A').mean()
# print(df_agrupado)