# Mais Exercícios de Python, NumPy e pandas

## Exercícios de Python

### 21. Crie uma função que receba uma string e retorne o número de vogais presentes na string.

In [40]:
import numpy as np
import pandas as pd
import random

In [7]:
def get_vogais(palavra):
    count = 0
    for letra in palavra:
        if letra in ["a", "e", "i", "o", "u"]:
            count += 1
    return count

print(get_vogais("paralelepipedo"))

def vogais(palavra):
    vogais = "aeiouAEIOU"
    return sum(1 for letra in palavra if letra in vogais)

print(vogais("paralelepipedo"))

7
7


In [ ]:
# Resposta:
def conta_vogais(s):
    vogais = 'aeiouAEIOU'
    return sum(1 for char in s if char in vogais)

print(conta_vogais('Exemplo de string'))

### 22. Crie uma lista de palavras e ordene-a em ordem alfabética.

In [8]:
lista = ["abacate", "mamao", "abacaxi"]
lista.sort()
lista

['abacate', 'abacaxi', 'mamao']

In [ ]:
# Resposta:
palavras = ['banana', 'abacaxi', 'laranja', 'manga']
palavras.sort()
print(palavras)

### 23. Crie uma função que receba um número e retorne True se for primo, caso contrário, False.

In [28]:
def is_primo(number):
    if number > 1:
        for i in range(2, number):
            if number % i == 0:
                print(number, 'não é primo')
                break
            else:
                print(number, 'é primo')
                break
    elif number <= 2:
        print(number, 'não é primo')


is_primo(2)

In [29]:
# Resposta:
def eh_primo(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

print(eh_primo(2))

True


### 24. Crie uma lista de dicionários com dados de alunos (nome, idade, nota) e ordene a lista pela nota em ordem decrescente.

In [39]:
alunos = [
    {'nome': 'Ana', 'idade': 20, 'nota': 85},
    {'nome': 'Bruno', 'idade': 22, 'nota': 90},
    {'nome': 'Carlos', 'idade': 21, 'nota': 88}
]

alunos.sort(key=lambda aluno: aluno['nota'], reverse=True)
alunos

[{'nome': 'Bruno', 'idade': 22, 'nota': 90},
 {'nome': 'Carlos', 'idade': 21, 'nota': 88},
 {'nome': 'Ana', 'idade': 20, 'nota': 85}]

In [ ]:
# Resposta:
alunos = [
    {'nome': 'Ana', 'idade': 20, 'nota': 85},
    {'nome': 'Bruno', 'idade': 22, 'nota': 90},
    {'nome': 'Carlos', 'idade': 21, 'nota': 88}
]
alunos.sort(key=lambda x: x['nota'], reverse=True)
print(alunos)

### 25. Crie um gerador que produza os números de 1 a 10.

In [59]:
ger = random.randint(1,11)
ger

7

In [60]:
# Resposta:
def gerador():
    for i in range(1, 11):
        yield i

for numero in gerador():
    print(numero)

1
2
3
4
5
6
7
8
9
10


## Exercícios de NumPy

### 26. Crie um array NumPy de 10 elementos igualmente espaçados entre 0 e 1 e exiba-o.

In [62]:
lista = np.linspace(0,1,10)
lista

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
# Resposta:
array_espaçado = np.linspace(0, 1, 10)
print(array_espaçado)

### 27. Crie um array NumPy com 20 números inteiros aleatórios entre 1 e 100 e exiba-o.

In [67]:
lista = np.random.randint(1,101,20)
lista

array([10, 85, 17, 58, 60, 65, 96, 91, 72, 47, 93,  6, 34, 87, 40, 21, 27,
       49, 95,  5])

In [ ]:
# Resposta:
array_aleatorio = np.random.randint(1, 101, 20)
print(array_aleatorio)

### 28. Encontre o valor mínimo e o valor máximo do array criado no exercício anterior e exiba-os.

In [69]:
print(np.min(lista), np.max(lista))

5 96


In [ ]:
# Resposta:
valor_minimo = np.min(array_aleatorio)
valor_maximo = np.max(array_aleatorio)
print(f'Mínimo: {valor_minimo}, Máximo: {valor_maximo}')

### 29. Calcule a variância e o desvio padrão dos valores do array criado no exercício 27 e exiba-os.

In [71]:
print(np.var(lista), np.std(lista))

967.79 31.109323361333335


In [ ]:
# Resposta:
variancia = np.var(array_aleatorio)
desvio_padrao = np.std(array_aleatorio)
print(f'Variância: {variancia}, Desvio Padrão: {desvio_padrao}')

### 30. Crie uma matriz 4x4 com valores de 0 a 15 e exiba-a.

In [72]:
mt = np.random.randint(0,16,(4,4))
mt

array([[11,  0, 14,  1],
       [ 9,  6,  3, 11],
       [10,  1, 15,  9],
       [11, 15,  4,  0]])

In [ ]:
# Resposta:
matriz = np.arange(16).reshape(4, 4)
print(matriz)

### 31. Calcule a transposta da matriz criada no exercício anterior e exiba-a.

In [73]:
mt.T

array([[11,  9, 10, 11],
       [ 0,  6,  1, 15],
       [14,  3, 15,  4],
       [ 1, 11,  9,  0]])

In [ ]:
# Resposta:
matriz_transposta = matriz.T
print(matriz_transposta)

### 32. Crie uma matriz 3x3 de valores booleanos onde True indica valores maiores que 5.

In [77]:
mb = mt > 5
print(mb)

m = np.arange(9).reshape(3,3) > 5
m

[[ True False  True False]
 [ True  True False  True]
 [ True False  True  True]
 [ True  True False False]]


array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [ ]:
# Resposta:
matriz_booleana = np.random.randint(1, 10, (3, 3)) > 5
print(matriz_booleana)

### 33. Crie um array de 10 elementos e substitua todos os valores pares por -1.

In [80]:
a = np.arange(10)
a[(a % 2 == 0)] = -1
a

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [ ]:
# Resposta:
array = np.arange(10)
array[array % 2 == 0] = -1
print(array)

## Exercícios de pandas

### 34. Carregue o arquivo CSV criado anteriormente para um DataFrame.

In [81]:
df = pd.read_csv("ex_19.csv")

A  B   C
0  1  4   7
1  2  5   8
2  3  6   9
3  1  7  10
4  2  8  11

In [ ]:
# Resposta:
df_csv = pd.read_csv('exercicio_19.csv')
print(df_csv)

### 35. Exiba as primeiras 5 linhas do DataFrame carregado.

In [82]:
df.head()

A  B   C
0  1  4   7
1  2  5   8
2  3  6   9
3  1  7  10
4  2  8  11

In [ ]:
# Resposta:
print(df_csv.head())

In [83]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

### 36. Exiba os nomes das colunas do DataFrame.

In [ ]:
# Resposta:
print(df_csv.columns)

### 37. Filtre as linhas do DataFrame onde o valor da coluna 'C' é maior que 10.

In [84]:
df[df["C"] > 10]

A  B   C
4  2  8  11
5  3  9  12

In [ ]:
# Resposta:
df_filtrado = df_csv[df_csv['C'] > 10]
print(df_filtrado)

### 38. Adicione uma nova coluna 'D' ao DataFrame com os valores sendo a soma das colunas 'B' e 'C'.

In [87]:
df["D"] = df["B"] + df["C"]
df

A  B   C   D
0  1  4   7  11
1  2  5   8  13
2  3  6   9  15
3  1  7  10  17
4  2  8  11  19
5  3  9  12  21

In [ ]:
# Resposta:
df_csv['D'] = df_csv['B'] + df_csv['C']
print(df_csv)

### 39. Remova a coluna 'A' do DataFrame.

In [90]:
df.drop("A", axis=1, inplace= True)
df

B   C   D
0  4   7  11
1  5   8  13
2  6   9  15
3  7  10  17
4  8  11  19
5  9  12  21

In [ ]:
# Resposta:
df_csv.drop('A', axis=1, inplace=True)
print(df_csv)

### 40. Renomeie a coluna 'D' para 'Total'.

In [92]:
df.rename(columns={'D': 'Total'}, inplace = True)
df

B   C  Total
0  4   7     11
1  5   8     13
2  6   9     15
3  7  10     17
4  8  11     19
5  9  12     21

In [ ]:
# Resposta:
df_csv.rename(columns={'D': 'Total'}, inplace=True)
print(df_csv)

### 41. Salve o DataFrame modificado em um novo arquivo CSV.

In [93]:
df.to_csv("novo_df.csv")

In [ ]:
# Resposta:
df_csv.to_csv('exercicio_41.csv', index=False)

### 42. Carregue o novo arquivo CSV para um DataFrame e exiba-o.

In [95]:
dfn = pd.read_csv("novo_df.csv")
dfn
dfn.drop('Unnamed: 0', axis=1, inplace=True)
dfn

B   C  Total
0  4   7     11
1  5   8     13
2  6   9     15
3  7  10     17
4  8  11     19
5  9  12     21

In [ ]:
# Resposta:
df_novo = pd.read_csv('exercicio_41.csv')
print(df_novo)

### 43. Agrupe o DataFrame pela coluna 'B' e exiba a média dos valores agrupados.

In [96]:
dfn.groupby("B").mean()

C  Total
B             
4   7.0   11.0
5   8.0   13.0
6   9.0   15.0
7  10.0   17.0
8  11.0   19.0
9  12.0   21.0

In [ ]:
# Resposta:
media_agrupada = df_novo.groupby('B').mean()
print(media_agrupada)

### 44. Exiba a quantidade de valores únicos na coluna 'C'.

In [100]:
dfn["C"].nunique()

6

In [ ]:
# Resposta:
valores_unicos = df_novo['C'].nunique()
print(valores_unicos)

### 45. Substitua os valores da coluna 'C' por 'Alto' se forem maiores que 10 e 'Baixo' caso contrário.

In [103]:
dfn["C"] = np.where(dfn["C"] > 10, "Alto", "Baixo")
dfn

B      C  Total
0  4  Baixo     11
1  5  Baixo     13
2  6  Baixo     15
3  7  Baixo     17
4  8   Alto     19
5  9   Alto     21

In [ ]:
# Resposta:
df_novo['C'] = df_novo['C'].apply(lambda x: 'Alto' if x > 10 else 'Baixo')
print(df_novo)

### 46. Crie um DataFrame a partir de um dicionário onde as chaves são nomes de frutas e os valores são suas respectivas quantidades.

In [107]:
dados_frutas = {'Maçã': 10, 'Banana': 20, 'Laranja': 15}
df = pd.DataFrame(list(dados_frutas.items()), columns=["Frutas", "Quantidades"])
df

Frutas  Quantidades
0     Maçã           10
1   Banana           20
2  Laranja           15

In [ ]:
# Resposta:
dados_frutas = {'Maçã': 10, 'Banana': 20, 'Laranja': 15}
df_frutas = pd.DataFrame(list(dados_frutas.items()), columns=['Fruta', 'Quantidade'])
print(df_frutas)

### 47. Crie um DataFrame a partir de listas de dados, onde cada lista representa uma linha do DataFrame.

In [109]:
lista = [["joao", 25, "M"],["maria", 23, "M"],["carla", 22, "P"]]
df = pd.DataFrame(lista, columns=['Nome', 'Idade', "Tamanho"])
df

Nome  Idade Tamanho
0   joao     25       M
1  maria     23       M
2  carla     22       P

In [ ]:
# Resposta:
dados_linhas = [
    ['João', 25, 'M'],
    ['Ana', 22, 'F'],
    ['Carlos', 30, 'M']
]
df_linhas = pd.DataFrame(dados_linhas, columns=['Nome', 'Idade', 'Sexo'])
print(df_linhas)

### 48. Exiba o tipo de dados de cada coluna do DataFrame criado no exercício anterior.

In [110]:
df.dtypes

Nome       object
Idade       int64
Tamanho    object
dtype: object

In [ ]:
# Resposta:
print(df_linhas.dtypes)

### 49. Converta a coluna 'Idade' do DataFrame anterior para o tipo float.

In [111]:
df['Idade'] = df['Idade'].astype(float)
df.dtypes

Nome        object
Idade      float64
Tamanho     object
dtype: object

In [ ]:
# Resposta:
df_linhas['Idade'] = df_linhas['Idade'].astype(float)
print(df_linhas.dtypes)

### 50. Calcule a idade média dos indivíduos no DataFrame criado no exercício 47.

In [114]:
df["Idade"].mean()

23.333333333333332

In [ ]:
# Resposta:
idade_media = df_linhas['Idade'].mean()
print(idade_media)