# NumPy - Numerical Python

## Criando arrays NumPy

In [5]:
!pip install numpy
# Importando o NumPy
import numpy as np

### Criando arrays de 1 dimensão

In [6]:
a1D = np.array([1, 2, 3])
a1D

array([1, 2, 3])

In [7]:
# O objeto criado é um ndarray: n-dimensional array
type(a1D)

numpy.ndarray

In [8]:
# Verificando o tipo dos elementos
a1D.dtype

dtype('int32')

In [9]:
b1D = np.array([1, 2, 3], dtype = float)
b1D

array([1., 2., 3.])

In [10]:
b1D.dtype

dtype('float64')

In [11]:
c1D = np.array([1, 2, 3], dtype = str)
c1D

array(['1', '2', '3'], dtype='<U1')

In [12]:
# str > float > int > bool
d1D = np.array([1, 3.14, "NumPy", True])
d1D

array(['1', '3.14', 'NumPy', 'True'], dtype='<U32')

In [13]:
e1D = np.array([1, 3.14, False, True])
e1D

array([1.  , 3.14, 0.  , 1.  ])

In [14]:
e1D.dtype

dtype('float64')

In [15]:
f1D = np.array([1, False, True])
f1D

array([1, 0, 1])

In [16]:
f1D.dtype

dtype('int32')

In [17]:
g1D = np.array([False, True])
g1D

array([False,  True])

In [18]:
g1D.dtype

dtype('bool')

### Criando arrays de 2 dimensões

In [19]:
a2D = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a2D.dtype

dtype('int32')

### Criando arrays de 3 dimensões

In [21]:
a3D = np.array( [ [ [1,2,3], [4,5,6], [7,8,9] ], [ [11,12,13], [14,15,16], [17,18,19] ], [ [21,22,23], [24,25,26], [27,28,29] ]])
a3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

## Outras formas de criar arrays

### Arrays preenchidos com zeros - zeros()

In [22]:
# 1 dimensão
azeros = np.zeros(5)
azeros

array([0., 0., 0., 0., 0.])

In [23]:
# 2 dimensões
bzeros = np.zeros((3, 4)) # 3 linhas e 4 colunas
bzeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# 3 dimensões
czeros = np.zeros((3, 4, 2)) # 3 páginas, 4 linhas e 2 colunas
czeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
# 2 dimensões
dzeros = np.zeros((3, 4), dtype = int) # 3 linhas e 4 colunas
dzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Arrays preenchidos com 1's - ones()

In [26]:
# 1 dimensão
a_um_1D = np.ones(5)
a_um_1D

array([1., 1., 1., 1., 1.])

In [27]:
b_um_1D = np.ones(10, dtype = str)
b_um_1D

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [28]:
c_um_1D = np.ones(5, dtype = int)
c_um_1D

array([1, 1, 1, 1, 1])

In [29]:
# 2 dimensões
d_um_2D = np.ones((4, 3)) # 4 linhas e 3 colunas
d_um_2D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# 3 dimensões
e_um_3D = np.ones((5, 2, 3)) 
e_um_3D

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
# 4 dimensões
f_um_4D = np.ones((3, 4, 2, 3)) 
f_um_4D

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

### Arrays preenchidos com faixas de valores - arange()

In [32]:
# Cria um ndarray preenchido com  os elementos de 0 a n-1
# No exemplo abaixo vai criar um ndarray com os elementos 0 a 9
a1D = np.arange(10)
a1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Cria um ndarray preenchido com os elementos variando entre o valor inicial e o valor final - 1
# Nesse exemplo vai criar um array com os elementos de 5 a 14
b1D = np.arange(5, 15)
b1D

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
# Cria um ndarray preenchido com os elementos variando entre o valor inicial e o valor final - 1, com um determinado step
# No exemplo vai criar um array com os elementos de 5 a 100, com passo 10. Ou seja: 5, 15, 25...95
c1D = np.arange(5,100, 10)
c1D

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

### Criando arrays preenchidos com valores igualmente espaçados - linspace()

In [35]:
# Cria um array com n elementos entre o valor inicial e valor final, igualmente espaçados
d1D = np.linspace(0,10, 2) # Cria um array com 2 valores entre 0 e 10
d1D

array([ 0., 10.])

In [36]:
e1D = np.linspace(0,10, 4) # Cria um array com 2 valores entre 0 e 10
e1D

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [37]:
f1D = np.linspace(1,1000) # Se não for passada a quantidade de elementos, o padrão é gerar 50 elementos
f1D

array([   1.        ,   21.3877551 ,   41.7755102 ,   62.16326531,
         82.55102041,  102.93877551,  123.32653061,  143.71428571,
        164.10204082,  184.48979592,  204.87755102,  225.26530612,
        245.65306122,  266.04081633,  286.42857143,  306.81632653,
        327.20408163,  347.59183673,  367.97959184,  388.36734694,
        408.75510204,  429.14285714,  449.53061224,  469.91836735,
        490.30612245,  510.69387755,  531.08163265,  551.46938776,
        571.85714286,  592.24489796,  612.63265306,  633.02040816,
        653.40816327,  673.79591837,  694.18367347,  714.57142857,
        734.95918367,  755.34693878,  775.73469388,  796.12244898,
        816.51020408,  836.89795918,  857.28571429,  877.67346939,
        898.06122449,  918.44897959,  938.83673469,  959.2244898 ,
        979.6122449 , 1000.        ])

In [38]:
g1D = np.linspace(1,1000, dtype = int) # gerando int, a função simplesmente corta as casas decimais
g1D

array([   1,   21,   41,   62,   82,  102,  123,  143,  164,  184,  204,
        225,  245,  266,  286,  306,  327,  347,  367,  388,  408,  429,
        449,  469,  490,  510,  531,  551,  571,  592,  612,  633,  653,
        673,  694,  714,  734,  755,  775,  796,  816,  836,  857,  877,
        898,  918,  938,  959,  979, 1000])

In [39]:
h1D = np.linspace(0,50, 10, endpoint = True) # O valor final é incluído
h1D


array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [40]:
i1D = np.linspace(0,50, 10, endpoint = False) # O valor final não é incluído
i1D

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

### Criando arrays preenchidos com um único valor passado por parâmetro - full()

In [41]:
a1D = np.full(10, 5) # ndarray contendo 10 números 5
a1D

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [42]:
a2D = np.full((3, 5), 3)  # ndarray de 3 linhas e 5 colunas contendo o número 3
a2D

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [43]:
a3D = np.full((3, 5, 8), -1)  # ndarray de 3 páginas, 5 linhas e 8 colunas contendo o número -1
a3D

array([[[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]]])

### Criando matriz identidade - eye()

In [44]:
ident = np.eye(5) # Cria uma matriz 5x5 preenchida com 1s na diagonal principal e 0 nas posições restantes
ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Criando matriz com elementos aleatórios

In [45]:
a1D = np.random.randint(0, 100, 10) # Cria um ndarray com 10 elementos entre 0 e 99
a1D

array([38, 67, 55, 91, 64, 76, 42, 74, 61, 78])

In [46]:
a2D = np.random.randint(1, 500, (4,5))
a2D

array([[270, 179, 485, 220, 276],
       [494, 121, 456, 223, 103],
       [277, 412,  51, 368,  40],
       [203,  64, 473, 368, 259]])

In [47]:
# Gerando 10 combinações para a mega-sena
# Valores vão de 1 a 60, 10 páginas, 1 linha, 6 colunas
a3D = np.random.randint(1,61,(10,1,6)) 
a3D

array([[[49, 18, 32, 44, 21, 21]],

       [[ 5, 60, 32, 32, 37,  3]],

       [[39,  8, 31, 56, 15, 37]],

       [[32, 40,  6, 39, 42,  5]],

       [[11, 11, 16, 26, 51, 53]],

       [[19, 49, 59, 16, 37, 39]],

       [[14, 37, 34,  6,  8, 28]],

       [[20, 37, 24, 49,  5, 40]],

       [[ 7, 55, 42, 33, 21, 28]],

       [[39, 51, 13,  1, 13, 42]]])

In [48]:
b1D = np.random.random(10) # Cria um ndarray contendo 10 elementos aleatórios entre 0 e 1
b1D

array([0.75153705, 0.28925013, 0.74930915, 0.10032536, 0.87285745,
       0.97565193, 0.41096671, 0.88836435, 0.14893949, 0.68110504])

In [49]:
c2D = np.random.random((4,5)) # Cria um ndarray de 4 linhas e 5 colunas contendo elementos aleatórios entre 0 e 1
c2D

array([[0.12802031, 0.24940993, 0.61814988, 0.02712779, 0.52638577],
       [0.2659174 , 0.90135283, 0.16638875, 0.96948198, 0.29160994],
       [0.8899819 , 0.96691607, 0.82202156, 0.57759886, 0.50947007],
       [0.9064091 , 0.9480967 , 0.27530187, 0.06678732, 0.68212096]])